//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using KSP;

namespace LayeredAnimations
{
	public class ModuleLayeredAnimator : ModuleAnimateGeneric
	{
		[KSPField]
		public int layer = 1;

		public ModuleLayeredAnimator ()
		{
		}

		public override void OnStart (StartState state)
		{
			base.OnStart (state);

			this.anim[this.animationName].layer = layer;
		}
	}
}

